version: '3.8'

services:
    app:
        build: .
        image: swoole-app
        container_name: swoole-app
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/app
            - ./docker/local/supervisor/supervisord.conf:/etc/supervisord.conf
            - ./docker/local/php/octane.ini:/usr/local/etc/php/conf.d/99-octane.ini
            - ./docker/local/nginx/default.conf:/etc/nginx/http.d/default.conf
        networks:
            - swoole-network

    db:
        image: postgres
        container_name: swoole-db
        environment:
            POSTGRES_DB: swoole
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./storage/db:/var/lib/postgresql/data
        networks:
            - swoole-network
networks:
    swoole-network:
        driver: bridge
